In [1]:
#!pip install transformers
#!pip install tiffslide
import utils_gbm
import pickle as pkl
import torch

In [2]:
from gbmhackathon import MosaicDataset
source_dict_mosaic = MosaicDataset.load_tabular()
dict_he=source_dict_mosaic["he"] ## source_dict_mosaic["he"]=dict_keys(['HE files', 'H1 features'])
HE_files,H1_features=dict_he["HE files"], dict_he["H1 features"]


In [3]:
print(H1_features) 



                                                         path patient id
Subject Id                                                              
HK_G_001a   /home/ec2-user/SageMaker/data/h1_bioptimus_fea...   HK_G_001
HK_G_002a   /home/ec2-user/SageMaker/data/h1_bioptimus_fea...   HK_G_002
HK_G_003a   /home/ec2-user/SageMaker/data/h1_bioptimus_fea...   HK_G_003
HK_G_004a   /home/ec2-user/SageMaker/data/h1_bioptimus_fea...   HK_G_004
HK_G_005a   /home/ec2-user/SageMaker/data/h1_bioptimus_fea...   HK_G_005
...                                                       ...        ...
HK_G_107a   /home/ec2-user/SageMaker/data/h1_bioptimus_fea...   HK_G_107
HK_G_111b   /home/ec2-user/SageMaker/data/h1_bioptimus_fea...   HK_G_111
HK_G_112a   /home/ec2-user/SageMaker/data/h1_bioptimus_fea...   HK_G_112
HK_G_114a   /home/ec2-user/SageMaker/data/h1_bioptimus_fea...   HK_G_114
HK_G_115b   /home/ec2-user/SageMaker/data/h1_bioptimus_fea...   HK_G_115

[81 rows x 2 columns]


In [4]:
with open("novae_emb_dict.pkl", "rb") as f:
    emb_novae = pkl.load(f)
with open("dict_embedding_c.pkl", "rb") as f:
    emb_c = pkl.load(f)
dset=utils_gbm.custom_dataset(HE_files,torch.load("tenseur_embedding_phitonv2.pt"),emb_novae,emb_c) 


Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.


In [5]:
for i in range(80) : 
    
    if dset.__getitem__(i) is None : 
        print(i)


33
38
64
73
75
76
79


In [6]:
emb_c.keys()

dict_keys(['HK_G_001a', 'HK_G_002a', 'HK_G_003a', 'HK_G_004a', 'HK_G_005a', 'HK_G_006a', 'HK_G_007a', 'HK_G_008a', 'HK_G_009a', 'HK_G_010a', 'HK_G_011a', 'HK_G_012a', 'HK_G_013a', 'HK_G_014a', 'HK_G_015a', 'HK_G_016a', 'HK_G_017b', 'HK_G_018a', 'HK_G_019a', 'HK_G_020a', 'HK_G_021a', 'HK_G_022a', 'HK_G_023a', 'HK_G_024a', 'HK_G_025a', 'HK_G_026a', 'HK_G_027a', 'HK_G_028a', 'HK_G_029b', 'HK_G_030a', 'HK_G_031a', 'HK_G_032a', 'HK_G_033a', 'HK_G_034a', 'HK_G_035a', 'HK_G_036b', 'HK_G_037a', 'HK_G_038a', 'HK_G_039a', 'HK_G_040a', 'HK_G_041a', 'HK_G_042a', 'HK_G_043a', 'HK_G_044b', 'HK_G_045a', 'HK_G_046a', 'HK_G_047a', 'HK_G_048a', 'HK_G_049a', 'HK_G_050a', 'HK_G_051a', 'HK_G_052a', 'HK_G_053a', 'HK_G_054a', 'HK_G_055a', 'HK_G_056a', 'HK_G_057a', 'HK_G_058a', 'HK_G_059b', 'HK_G_060a', 'HK_G_061b', 'HK_G_062a', 'HK_G_063a', 'HK_G_064a', 'HK_G_065a', 'HK_G_066a', 'HK_G_067a', 'HK_G_068a', 'HK_G_069a', 'HK_G_070a', 'HK_G_072a', 'HK_G_073a', 'HK_G_075a', 'HK_G_076a', 'HK_G_078a', 'HK_G_079b', '

In [7]:
from torch.utils.data import DataLoader

In [8]:
dloader=DataLoader(dset,collate_fn=utils_gbm.custom_collate_fn,batch_size=4) 

In [9]:
dloader

In [10]:
next(iter(dloader))

[('HK_G_001a',
  tensor([ 0.1128, -0.3456, -0.0970,  ...,  0.1700,  0.2618, -0.1506]),
  array([[-0.31912524, -0.11272641,  0.2837144 , ..., -0.09955969,
           0.03288715, -0.36776334],
         [-0.3330066 , -0.03813721,  0.26050317, ..., -0.15780449,
           0.03129857, -0.29435375],
         [ 0.12384544,  0.11602774,  0.44294336, ..., -0.402109  ,
          -0.19718835, -0.04662852],
         ...,
         [-0.23171404, -0.13475265,  0.3546657 , ..., -0.05644633,
           0.12796688, -0.40540335],
         [ 0.34226498,  0.10448818,  0.3366263 , ..., -0.48089442,
          -0.24782735, -0.01127741],
         [-0.34072948, -0.00999007,  0.27253863, ..., -0.10768241,
           0.00071271, -0.33029935]], dtype=float32),
  tensor([ 0.2964, -0.3047, -0.4976,  0.1129, -0.3132,  0.2259, -0.3958, -0.5512,
           0.3165,  0.1710,  0.3456,  0.1055,  0.2759, -0.1251,  0.4415,  0.3482,
          -0.0402,  0.2798,  0.1872, -0.3473, -0.2127,  0.0388,  0.0254,  0.2111,
          -0

In [16]:
for i in range(10) : 
    a=dset[i]
    print(a[1].shape,a[2].shape,a[3].shape)

torch.Size([1024]) (1462, 64) torch.Size([64])
torch.Size([1024]) (4467, 64) torch.Size([64])
torch.Size([1024]) (2876, 64) torch.Size([64])
torch.Size([1024]) (2237, 64) torch.Size([64])
torch.Size([1024]) (3589, 64) torch.Size([64])
torch.Size([1024]) (4832, 64) torch.Size([64])
torch.Size([1024]) (4773, 64) torch.Size([64])
torch.Size([1024]) (4672, 64) torch.Size([64])
torch.Size([1024]) (4583, 64) torch.Size([64])
torch.Size([1024]) (2771, 64) torch.Size([64])


In [12]:
dset[45]


('HK_G_047a',
 tensor([-0.0539, -0.5297, -0.0642,  ...,  0.1789,  0.2197,  0.0056]),
 array([[-0.08014719,  0.0226677 ,  0.38683406, ..., -0.45547077,
         -0.20303065,  0.0350931 ],
        [-0.24648541,  0.04048198,  0.2664573 , ..., -0.26297712,
         -0.24758446,  0.00399087],
        [ 0.03167073, -0.05216624,  0.19348897, ..., -0.43161196,
         -0.44735575, -0.07595025],
        ...,
        [ 0.20879792,  0.14114872,  0.25307524, ..., -0.5615834 ,
         -0.39529395, -0.12393145],
        [-0.27814874, -0.04083267,  0.2853797 , ..., -0.2901719 ,
         -0.30477586, -0.09112598],
        [ 0.09548052, -0.11962387,  0.20562878, ..., -0.44987673,
         -0.3828746 , -0.13531055]], dtype=float32),
 tensor([ 0.4144,  0.1532,  0.2813, -0.1155, -0.1642,  0.4287, -0.3540, -0.2343,
          0.2888, -0.1073,  0.4480, -0.2075,  0.4261, -0.2090,  0.3310,  0.4626,
         -0.0562,  0.4025,  0.3577, -0.1854, -0.0333, -0.3231,  0.2222,  0.2143,
         -0.1169,  0.1423, -0.